spring.application.name=pdf-rag-chatbot
spring.datasource.url=jdbc:mysql://localhost:3306/pdf_rag_chatbot

spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=gemini.api.key=PASTE_YOUR_API_KEY_HERE